version: "3.8"

services:
  # keycloak:
  #   image: quay.io/keycloak/keycloak:20.0.3
  #   restart: unless-stopped
  #   env_file: ./.env
  #   environment:
  #     - KEYCLOAK_ADMIN=$KEYCLOAK_ADMIN
  #     - KEYCLOAK_ADMIN_PASSWORD=$KEYCLOAK_ADMIN_PASSWORD
  #     - KC_HTTPS_CERTIFICATE_FILE=$KC_HTTPS_CERTIFICATE_FILE
  #     - KC_HTTPS_CERTIFICATE_KEY_FILE=$KC_HTTPS_CERTIFICATE_KEY_FILE
  #   volumes:
  #     - ./certs/idp:/opt/keycloak/conf
  #   command:
  #     - start-dev
  #   ports: 
  #     - 8843:8443
  #     - 8890:8080
  client:
    build: ./client
    restart: unless-stopped
    ports: 
      - 8181:80
  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db
  app:
    depends_on:
      - mongodb
    build: ./app
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    stdin_open: true
    tty: true
volumes:
  db:
